### ISSUE TITLE
Creating a new Logo for RecursiveLaughter

### ISSUE THREAD

**Issue by Yasujizr** [unrealGuthrie/rela#1]
Hi, I saw your game. I wonder if you need a new logo. I can make one for you. How would you like a design. Or is it a design presentation myself?

**Comment by unrealGuthrie** [comment]
Hey there.
Yes, i really would like to have a new Logo.
But for further discussions, i would prefer switching to Discord and continue writing there.
Hope that's ok.

[https://discord.gg/b5Bum5E](url)
